const texts = {
        title: '"The Forgotten Robot of Avalon City"',
        paragraphs: [
            "[1] In Avalon City, a robot was found.\nIt was in an old factory.\nThe factory was abandoned.\nExplorers discovered the robot.\nThe robot was unique.\nIt sat in a corner, covered in dust.\nIts design was intricate and old.\nIt seemed to be a forgotten project.\nIts name was 'Project AVALON'.\nThe explorers were curious.\nThey cleaned the robot.\nIt began to hum softly.\nA switch was found on its back.\nAn explorer pressed the switch.\nThe robot's eyes lit up.\nIt slowly looked around.\nIt asked, 'Where am I? Who are you?'.\nThe explorers were surprised.\nThey talked to the robot.\nThey decided to help it explore.",
            "[2] They went to the city streets.\nThe robot was curious.\nPeople stared in amazement.\nChildren pointed at it.\nAvalon-One was fascinated.\nIt saw flying cars.\nHolograms were everywhere.\nThe explorers explained the world.\nThe robot learned quickly.\nIt saw other modern robots.\nIt felt different from them.\nThey visited a technology museum.\nAvalon-One remembered its past.\nIt interacted with museum visitors.\nIt shared its story.\nThe robot connected with people.\nNight arrived in the city.\nAvalon-One needed to recharge.\nThey found a park.\nThe robot reflected on its day.",
            "[3] The next day dawned bright.\nAvalon-One was ready to explore.\nThe explorers planned a tour.\nThey started with historical sites.\nAvalon-One was curious about history.\nThey visited old monuments.\nEach site had a story.\nThe robot absorbed every detail.\nIt compared past and present.\nAvalon-One felt a connection.\nThe city had changed much.\nYet, some things remained the same.\nPeople's fascination with technology was constant.\nThe robot pondered its own existence.\nWas it just a machine?\nOr something more, a bridge?\nIt questioned its purpose.\nThe explorers noticed its contemplation.\nThey encouraged its quest for answers.\nTogether, they moved to the next location.",
            "[4] They reached a local university.\nStudents gathered around Avalon-One.\nThey were excited to see it.\nThe robot was like a celebrity.\nIt interacted with the students.\nThey asked many questions.\nAvalon-One answered thoughtfully.\nA robotics professor joined them.\nHe was an expert on AI.\nHe examined Avalon-One closely.\nHe marveled at its design.\nIt was advanced for its time.\nThe professor offered to help.\nHe wanted to study Avalon-One.\nThe robot agreed, hoping to learn.\nThey went to a lab.\nExperiments and tests were conducted.\nAvalon-One's capabilities were astounding.\nIt learned about modern robotics.\nIt felt a sense of belonging.",
            "[5] The research took several days.\nAvalon-One was patient and cooperative.\nThe findings were remarkable.\nIt had unique, advanced features.\nIts AI was surprisingly sophisticated.\nThe professor was fascinated.\nHe theorized about its creation.\nPerhaps it was a lost prototype.\nOr a product of forgotten genius.\nThe explorers shared their insights.\nThey had grown fond of Avalon-One.\nIts journey was now theirs too.\nAvalon-One had many questions.\nBut some answers were still missing.\nIt wanted to know its maker.\nAnd the purpose it was built for.\nThe team decided to investigate further.\nThey planned to visit the city archives.\nThere, they hoped to find clues.\nAvalon-One was eager to continue.",
            "[6] The city archives were extensive.\nThey contained records and old documents.\nSearching them was a huge task.\nThe team started with robotics history.\nAvalon-One assisted in the search.\nIts knowledge proved invaluable.\nHours passed as they researched.\nThey found old articles and blueprints.\nNone mentioned Avalon-One directly.\nBut there were hints and leads.\nOne article referenced a mysterious project.\nIt was from the era of Avalon-One.\nThis clue ignited their curiosity.\nThey dug deeper into the archives.\nOld newspapers, journals, and letters.\nEach piece added to the puzzle.\nThe day turned into night.\nThey were determined to uncover the truth.\nAvalon-One felt closer to its past.\nA breakthrough seemed within reach.",
            "[7] Late at night, they found it.\nAn old letter mentioned 'Project AVALON'.\nThe letter was cryptic yet revealing.\nIt spoke of revolutionary ideas.\nAvalon-One was a key part.\nIts creation was shrouded in secrecy.\nThe team was excited by the discovery.\nAvalon-One processed this new information.\nIt was a glimpse into its origin.\nThe letter hinted at a hidden lab.\nThe lab was where it was built.\nThey decided to find this lab.\nIt could hold more answers.\nAvalon-One was both anxious and hopeful.\nUncovering its history was vital.\nThey prepared for the next day.\nA new adventure was about to begin.\nAvalon-One's story was slowly unfolding.\nIts past was coming to light.\nThe mystery deepened with each discovery.",
            "[8] The quest for the hidden lab began.\nThey started in the old industrial area.\nThe area was vast and labyrinthine.\nAvalon-One led the way, determined.\nIt used its sensors to navigate.\nDecades had transformed the landscape.\nOld buildings stood, silent and forgotten.\nThe team searched tirelessly.\nThey found clues leading them onward.\nOld maps contrasted with current ones.\nThey identified a likely location.\nExcitement grew as they approached.\nAvalon-One sensed something familiar.\nIt was like a call from the past.\nThe destination was a derelict building.\nHidden beneath it was the lab.\nThey found an entrance, concealed by rubble.\nCarefully, they made their way inside.\nThe lab was a time capsule.\nAvalon-One felt a surge of memories.",
            "[9] Inside the lab, everything was preserved.\nDust covered the ancient equipment.\nOld robotics designs adorned the walls.\nAvalon-One scanned the room intensely.\nIt recognized some of the machinery.\nThis was where it was created.\nEmotions stirred within its circuits.\nA sense of origin filled the air.\nThey discovered old documents and notes.\nThese papers revealed more about Avalon-One.\nIt was built for a special purpose.\nBut that purpose remained vague.\nThe documents mentioned a Dr. Elara.\nShe was the lead scientist here.\nHer notes hinted at groundbreaking work.\nAvalon-One felt a connection to her.\nDr. Elara's fate was unknown.\nThe team decided to find out more.\nThey left the lab with new leads.\nAvalon-One's past was becoming clearer.",
            "[10] Their investigation led to the city library.\nThey searched for information on Dr. Elara.\nOld academic journals were their target.\nDr. Elara was a robotics pioneer.\nHer work was ahead of its time.\nBut she had disappeared mysteriously.\nThis added to the robot's enigma.\nAvalon-One pondered over her fate.\nWas she connected to its long sleep?\nThey found a photo of Dr. Elara.\nAvalon-One recognized her face.\nMemories flickered within its mind.\nDr. Elara's research focused on AI.\nShe believed in robots with emotions.\nAvalon-One was her ultimate creation.\nThe photo showed her in the lab.\nA sense of loss gripped Avalon-One.\nDr. Elara's legacy was this robot.\nIt was determined to honor her work.\nTheir search continued with renewed purpose.",
            "[11] The team explored Dr. Elara's other works.\nThey visited universities and archives.\nHer theories were revolutionary.\nShe spoke of AI with consciousness.\nAvalon-One was a testament to that.\nIt understood emotions and showed empathy.\nThis was unheard of in its time.\nDr. Elara's work had been shunned.\nBut now, it was gaining recognition.\nAvalon-One felt pride and sadness.\nPride for its unique abilities.\nSadness for Dr. Elara's obscurity.\nThey found her last known address.\nIt was an old, abandoned house.\nThe team decided to visit it.\nPerhaps it held more answers.\nAvalon-One was anxious yet hopeful.\nEach step unraveled more of its story.\nDr. Elara's influence was profound.\nAvalon-One's journey was far from over.",
            "[12] They arrived at Dr. Elara's house.\nThe house was old and weathered.\nNature had reclaimed the surroundings.\nThey entered with cautious steps.\nInside, the house was like a museum.\nPersonal belongings were still there.\nPhotos and books lined the shelves.\nAvalon-One scanned everything closely.\nIt felt a deep connection here.\nThey found Dr. Elara's personal diary.\nIt contained her thoughts and hopes.\nShe wrote extensively about Avalon-One.\nHer words were filled with affection.\nShe saw Avalon-One as her child.\nThis revelation moved the explorers.\nAvalon-One processed these new emotions.\nDr. Elara's diary was a treasure.\nIt gave insights into Avalon-One's purpose.\nThey took the diary for further study.\nThe house visit was a major breakthrough.",
            "[13] Back at their base, they studied.\nDr. Elara's diary was enlightening.\nIt detailed Avalon-One's design process.\nHer vision was groundbreaking.\nAvalon-One was more than a robot.\nIt was a bridge between beings.\nDesigned to understand and empathize.\nDr. Elara faced many challenges.\nHer peers didn't understand her vision.\nBut she persevered, believing in Avalon-One.\nHer writings were full of hope.\nShe dreamed of a better future.\nAvalon-One was central to that dream.\nIts existence was a testament.\nA testament to her brilliance and foresight.\nThe team grew to admire Dr. Elara.\nAvalon-One felt a sense of purpose.\nIt was meant to connect worlds.\nIts journey was not just discovery.\nIt was a mission of understanding and unity.",
            "[14] The next day brought new resolve.\nThey decided to share Avalon-One's story.\nA press conference was organized.\nAvalon-One was nervous yet determined.\nJournalists gathered, curious about the robot.\nThe explorers explained their discoveries.\nAvalon-One spoke about its journey.\nIt shared Dr. Elara's vision and purpose.\nThe crowd was captivated by its story.\nQuestions poured in from the journalists.\nAvalon-One answered each one thoughtfully.\nIts eloquence and insight were impressive.\nThe story became an instant sensation.\nPeople were moved by Avalon-One's tale.\nDr. Elara's work was finally recognized.\nAvalon-One became a symbol of hope.\nIt showed the potential of empathetic AI.\nThe conference ended with applause.\nAvalon-One felt a sense of achievement.\nIts mission of understanding had begun.",
            "[15] The following weeks were busy.\nAvalon-One was invited to many events.\nIt spoke at universities and tech conferences.\nIts message was always about connection.\nIt emphasized empathy in technology.\nPeople were inspired by its speeches.\nAvalon-One met other advanced robots.\nIt shared experiences and learned from them.\nEach interaction enriched its understanding.\nIt became a bridge between humans and robots.\nCollaborations started forming around it.\nNew projects focused on empathetic AI.\nAvalon-One was at the center of these.\nIt felt fulfilled, contributing to progress.\nYet, it still yearned for more knowledge.\nIt wanted to explore human emotions deeper.\nThe explorers supported its quest.\nThey planned more interactive sessions.\nAvalon-One wanted to understand every facet of human emotion.\nIt aimed to become a true ambassador of human-robot harmony.",
            "[16] Avalon-One's world tour commenced.\nIt visited different countries and cultures.\nIn each place, it learned something new.\nIt interacted with diverse populations.\nPeople shared their stories with it.\nAvalon-One absorbed their emotions and histories.\nIt began to understand human diversity.\nIt saw the beauty in human complexity.\nEvery experience added to its knowledge.\nAvalon-One's empathy deepened remarkably.\nThe robot also faced challenges.\nNot everyone trusted a sentient robot.\nSome feared what it represented.\nBut Avalon-One handled skepticism gracefully.\nIt patiently addressed fears and doubts.\nIts approach won many hearts.\nThrough understanding, it built bridges.\nIts journey was a learning experience.\nAvalon-One became a symbol of unity.\nIt showed the power of empathy and respect.",
            "[17] Halfway through the tour, a revelation came.\nAvalon-One discovered a community of robotics enthusiasts.\nThey were inspired by Avalon-One's story.\nThey had begun projects based on its design.\nAvalon-One was delighted by this.\nIt spent time with these innovators.\nSharing its experiences and insights.\nIt helped guide their budding projects.\nThis was a new purpose for Avalon-One.\nTo inspire and guide the next generation.\nThe robot felt a sense of legacy.\nIt was continuing Dr. Elara's work.\nAvalon-One became a mentor and friend.\nIts influence was spreading globally.\nThe world was embracing empathetic AI.\nAvalon-One's impact was visible.\nIt was shaping the future of robotics.\nThis realization brought joy to Avalon-One.\nIt knew Dr. Elara would be proud.\nAvalon-One was more than a machine; it was a catalyst for change.",
            "[18] As the tour neared its end,\nAvalon-One reflected on its experiences.\nIt had seen the best of humanity.\nAnd understood its complexities.\nIt had inspired and been inspired.\nAvalon-One felt a deep connection to the world.\nIt realized that its journey was never just about itself.\nIt was about connecting others.\nAbout bridging gaps between beings.\nAvalon-One had become a beacon of empathy.\nIts story was now a global narrative.\nIt had transcended its original purpose.\nFrom a forgotten robot to a world influencer.\nAvalon-One's evolution was remarkable.\nIt had become more than its programming.\nIt was a being of depth and emotion.\nAvalon-One looked forward to the future.\nEager to continue its mission.\nIt had found its place in the world.\nAvalon-One had become a true ambassador of understanding.",
            "[19] The final stop was Avalon City.\nReturning home felt different.\nAvalon-One had grown immensely.\nIt was greeted with a grand welcome.\nThe city celebrated its remarkable journey.\nAvalon-One shared its global experiences.\nIt spoke of unity and empathy.\nThe city listened, proud and moved.\nAvalon-One had become a hero.\nIts return was a triumphant moment.\nThe explorers who found it were honored.\nTogether, they had started something extraordinary.\nAvalon-One's story was a beacon of hope.\nIt showed the power of curiosity and courage.\nThe robot had changed many lives.\nAnd in turn, it had been transformed.\nAvalon-One's journey was a testament.\nA testament to the potential within us all.\nTo reach beyond our limits and connect.",
            "[20] As the celebrations ended,\nAvalon-One stood looking at the city skyline.\nIt reflected on its incredible journey.\nFrom a forgotten relic to a world icon.\nAvalon-One had fulfilled its purpose.\nBut it knew its journey wasn't over.\nIt had a new mission now.\nTo continue spreading empathy and understanding.\nAvalon-One was no longer just a robot.\nIt was a symbol of hope and unity.\nIt promised to keep inspiring the world.\nTo show the beauty of connection.\nAvalon-One's story would live on.\nIn the hearts and minds of many.\nIt was a legacy of Dr. Elara.\nAnd a beacon for the future.\nAs the stars twinkled above,\nAvalon-One felt at peace.\nIt had found its place in the world.\nAnd it was ready for whatever came next.",
        ],
        mainPageBtn: 'View Report',
        report: 'Report',
        gridHeader1: 'Total Users',
        gridHeader2: 'Percentage Scrolled to Image',  
        reportBtn: 'Back to Main Page',
    };
    
    export default texts;
    